image: Visual Studio 2017
version: 1.0.{build}-{branch}
skip_branch_with_pr: true

configuration: Release

before_build:
  - dotnet restore

build_script:
  - dotnet build -f net451
  - dotnet publish -f netcoreapp2.0

after_build:
  - 7z a "AutoSaliens_%APPVEYOR_BUILD_VERSION%_win.zip" "%APPVEYOR_BUILD_FOLDER%\AutoSaliens\bin\%CONFIGURATION%\net451\"
  - 7z rn "AutoSaliens_%APPVEYOR_BUILD_VERSION%_win.zip" net451 AutoSaliens
  - 7z a "AutoSaliens_%APPVEYOR_BUILD_VERSION%_portable.zip" "%APPVEYOR_BUILD_FOLDER%\AutoSaliens\bin\%CONFIGURATION%\netcoreapp2.0\publish\"
  - 7z rn "AutoSaliens_%APPVEYOR_BUILD_VERSION%_portable.zip" publish AutoSaliens

artifacts:
  - path: AutoSaliens_$(appveyor_build_version)_win.zip
    name: AutoSaliens $(appveyor_build_version) (Windows)
  - path: AutoSaliens_$(appveyor_build_version)_portable.zip
    name: AutoSaliens $(appveyor_build_version) (Portable)
